### PR TITLE
Bugfix - numpy debugger issues

### LINKED ISSUE #97: Cannot use an ide debugger with pybert.
**Describe the bug**
Numpy doesn't like the debugger and throws an exception.  The only way to debug seems to be print statements at the moment.  Running the script like you normally would doesn't cause the exception.  Seems like this thread has a few suggestions to resolve it.  https://stackoverflow.com/questions/24034839/valueerror-resizing-an-ndarray

**To Reproduce**
Run with debugging in any IDE such as vscode or pycharm.

**Screenshots**
```
Exception has occurred: ValueError
cannot resize an array that references or is referenced
by another array in this way.
Use the np.resize function or refcheck=False
  File "/git/PyBERT/pybert/pybert.py", line 1615, in calc_chnl_h
    temp.resize(len(t))
  File "/git/PyBERT/pybert/pybert_cntrl.py", line 183, in my_run_simulation
    chnl_h = self.calc_chnl_h()
  File "/git/PyBERT/pybert/pybert.py", line 643, in __init__
    my_run_simulation(self, initial_run=True)
  File "/git/PyBERT/pybert/__main__.py", line 6, in main
    thePyBERT = PyBERT()
  File "/git/PyBERT/pybert/__main__.py", line 10, in <module>
    main()
```

**Desktop (please complete the following information):**
 - OS: MacOS
 - IDE: vscode
 - PyBERT Version [latest]

### PR DESCRIPTION
**Pull request by jdpatt**
This will close #97 and allows using tools like vscode with pybert.

### CODE REVIEW

**Comment by capn-freako** [comment]
Thank you, @jdpatt !
I plan to catch up w/ all the work you've been doing, this weekend.
-db

**Comment by jdpatt** [comment]
No worries,  I plan to pick up one more or so that has been hanging around with some free time that I've had.

**Comment by capn-freako** [comment]
Awesome; thank you!
-db

**Comment by capn-freako** [comment]
I intend to attempt to merge this in, after pushing my own sandbox as: 3.5.0.0.

**Comment by capn-freako** [comment]
@jdpatt , I have to reject this PR, because the change you're proposing changes the program behavior, as per:

> If the new array is larger than the original array, then the new array is filled with repeated copies of a. Note that this behavior is different from a.resize(new_shape) which fills with zeros instead of repeated copies of a.

from: [NumPy resize() docs](https://numpy.org/doc/stable/reference/generated/numpy.resize.html)

In our case, we _must_ have the zero padding. :(

**Comment by jdpatt** [comment]
Ah, good catch! Let me copy that to the chaco issue as well. Bummer on vscode debugging though.

**Pull request closed without merging**
