### PR TITLE
WIP: Tx/Rx split resolving.

### PR DESCRIPTION
**Pull request by capn-freako**
Hi David,

Below are my thoughts on a possible way forward, which I'm currently coding up for demo purposes.
Please, let me know what you think.

Thanks!
-db

## Thoughts on how to proceed w/ development on `tx-rx-split` branch

Regarding the new v3.2.0 version of PyBERT (first one w/ new sub-tabbed layout), both David Patterson and I dislike the way the Tx/Rx configuration is currently split between the _Config._ and _Channel_ tabs.
The following are my thoughts on how to proceed.
We've created a branch: `tx-rx-split`, specifically for this work.

The obvious first impulse is to unify all Tx/Rx configuration, rather than have it split between two tabs.
However, I don't think it's quite that simple.
The problem is the Tx/Rx both have equalization-related *and* channel-related attributes.
For instance, the Tx output drive stage properties are intimately associated with the channel impulse response, while the Rx CTLE is closely associated w/ the CDR/DFE.
And the more I think about this, the more I believe that it makes sense to have the channel-related Tx/Rx attributes configured separately from the equalization-related attributes.
However, I think we may currently have the positions of those two sets flipped from what really makes sense.
I think I'd like to try the following and run it by David, to see what he thinks:

- Rename the *Channel* tab to *Equalization*.
- Swap the current positions of the Tx/Rx configuration items, placing the channel-related stuff on the Config. tab, and the equalization-related stuff on the (newly renamed) *Equalization* tab.
- Add the capability (on the *Config*. tab) to select an IBIS, or IBIS-AMI, model for either the Tx, or Rx, or both.
- If an IBIS model was selected, then use it to determine the impedance, etc. of the respective analog component, and don't make any changes to the *Equalization* tab.
- If an IBIS-AMI model was selected, then do as above, but also configure the *Equalization* tab to use the DLL/AMI files for equalization mdoeling of the Tx/Rx, as appropriate.

Also, I think David is correct: having a complete link picture somewhere in the GUI, which reflects the current configuration, would be very helpful.

### CODE REVIEW

**Comment by jdpatt** [comment]
I'm still a fan of having different tabs for each element: Config, Tx/Rx (Drivers, idk something descriptive), Channel, Optimizer and etc...  I agree the tx output is used to calculate the impulse but as a user but that relationship isn't in the forethought during initial setup.  For me(comparing to Hyperlynx), its usually:

1. Stimulus and Bit Pattern (Our config tab)
2. Make sure the channel is setup correctly. (Channel Tab)
3. Configure the Driver and Receiver including equalization or any AMI features (Our potential new Tab?)
4.  Sweep EQ settings (akin to our optimizer but realizing we can sweep in PyBERT as well.)
5. Results!

I think there is still valid reason to keep the channel information on its own tab especially with some of the simbeor work that you are doing.  Maybe one would want to run marigin analysis on the channel sweeping the impedance by x %.

**Comment by capn-freako** [comment]
Hi David,

Would you please pull my most recent commit to the `tx-rx-split` development branch and give it a whirl?

Note that the `PyAMI` submodule has also been updated.
So, you'll need to make sure it gets refreshed, as well.

Thanks!
-db

**Comment by capn-freako** [comment]
Oh, and if you find you have comments/questions/concerns, regarding the new `PyAMI` code specifically, here's the pull request for it:
https://github.com/capn-freako/PyAMI/pull/7

**Comment by capn-freako** [comment]
The following e-mail exchange took place between David Patterson and myself, in the final few days of bug fixing before performing this merge:

> Hi David,
> 
> I just pushed updates to both PyBERT(tx-rx-split branch) and PyAMI(ibis-parse branch).
> I’m now offering a more standard "IBIS file -> Component -> Pin -> Model" selection flow to the user.
> And I’d really like to expose this new machinery to lots of different IBIS(-AMI) files.
> Might you have time to help me w/ that?
> 
> Also, I’m hoping we can find time for a phone chat soon, to talk about how things are going and sync. up on what direction to move in, re: Tx/Rx GUI representation.
> Have you got any time for that this week?
> 
> Thanks!
> -db

> Hey, I'll pull that down and try with a handful of models that I have public access too.   A phone chat probably won't happen until Dec.  I've got a number of boards that we are trying to get artwork out, so that it gets built first thing after the holidays.
> 
> I can say that I've not completed any work/code review on the GUI representation or user submitted issues between other commitments.  I added the one pull request around config files for discussion as I was sun-setting that branch. (Was playing with the QT GUI framework and pybert over chaco/traitsui.)
> 
> David
> 

> Hi,
> 
> Thanks for getting back to me, despite your busy schedule! :)
> 
> Please, hold off on doing any testing against IBIS files.
> I started doing some myself, against random IBIS files found on the Web, and found a bunch of bugs I need to correct.
> I’ll let you know, as soon as I have something that I think is worth your time.
> 
> Oh my gosh! I’m so sorry; I completely forgot about that new pull request you submitted.
> I’ll get to it this weekend.
> 
> Thanks, again, for all your involvement, David!
> -db

> Sounds good, I’ll wait until then!
> 
> No problem, it may be something that we decide not to incorporate but I figure pickling isn’t a good long term solution.
> 
> David

> Hey,
> 
> Sorry, I just realized I never followed up on this.
> I believe the currently pushed code on the tx-rx-split branch is now correctly parsing IBIS model files.
> Please let me know what you find, in that regard.
> 
> Thanks,
> -db

> I haven’t pulled it since you were still debugging; I’ll add that to my list in addition to getting that hyper lynx sim.

> I did a fresh clone and install from the developer instructions.  Do I need to do anything special to switch to the tx-rx-split? 
> 
> Traceback (most recent call last):
>   File "/Users/davidpatterson/opt/anaconda3/envs/pybert/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/Users/davidpatterson/opt/anaconda3/envs/pybert/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/Users/davidpatterson/git/PyBERT/pybert/__main__.py", line 2, in <module>
>     from pybert.pybert      import PyBERT
>   File "/Users/davidpatterson/git/PyBERT/pybert/pybert.py", line 56, in <module>
>     from pyibisami.ibis_file import IBISModel
> ModuleNotFoundError: No module named ‘pyibisami.ibis_file'
> 
> I can see that file in the sub-folder PyAMI from cloning that branch.

> What output does this generate?:
> 
> python -c ‘import pyibisami as dut; print(dut.__file__)'

> (pybert) davidpatterson@Davids-MacBook git % python -c ‘import pyibisami as dut; print(dut.__file__)'
> quote>
> quote>

> Hmmm, try this: from within the PyBERT directory (not the pybert directory), execute:
> 
> conda develop PyAMI
> 
> -db

> “pip install PyAMI” solved it..
> 
> I like the layout, it definitely de-clutters it and we can forgo the additional tab.  I went to play with the new features but both random models I went to download failed to parse.
> DFE isn’t visible with the default window size.  I have to max my window to see the DFE settings.
> Screen Shot 2019-12-14 at 6.52.45 PM.png
> I just downloaded the first two models of parts that came to mind.  Both are valid ibis files.  Si52112.ibs failed to parse “No pin section”.TUSB1210.ibs failed to parse with just “NC”.  Both of these can be downloaded from Silicon labs or Texas Instruments site.
> It would be great if the pybert status updated with what it’s doing with the IBIS model.  I didn’t know if it was parsing or what until ~10 seconds later when the failed message popped up.
> 
> David

> Hmmm, I’m not sure you have what you need after a `pip install PyAMI`.
> I haven’t updated the PyPi repository in quite a while. (Guess I should do that.)
> That’s probably why you’re bumping into trouble.
> 
> If you wouldn’t mind, try the `conda develop` approach and see if your problems go away.
> 
> Thanks,
> -db

> What version number and date do you see in the Help => About tab?
> I’ve attached full screen shots of both that tab, as well as the Equalization tab, in my case.
> 
> Thanks,
> -db
>
> (Pictures omitted; PyBERT version reported: v3.3.0)

> Here’s what I get, for the Silicon Labs model:
> 
```
File "/Users/dbanas/Documents/Projects/PyBERT/PyAMI/pyibisami/ibis_parser.py", line 300, in comp
  return {nm: Component(dict(res))}
File "/Users/dbanas/Documents/Projects/PyBERT/PyAMI/pyibisami/ibis_model.py", line 55, in __init__
  raise LookupError("Missing [Pin]!")
LookupError: Missing [Pin]!
```
> 
> Looking into it now.
> 
> -db

> Hi David,
> 
> I just pushed a fix (to PyAMI) that results in both models you’ve identified now parsing correctly.
> 
> I’m curious about something, re: Git submodules, and am wondering if you’d mind playing guinea pig here.
> I’ve got PyAMI as a submodule of PyBERT. And I’m wondering if just pulling the new push to PyBERT alone is enough to cause the PyAMI submodule to also refresh.
> Of course, to try this experiment you’d have had to have done the `conda develop PyAMI` command I suggested. If you haven’t done that this experiment is pointless.
> 
> Looking forward to hearing about your test results,
> -db

> I should be able to give that a go tonight before we leave for the holidays tomorrow!

> Thanks, David!
> 
> Happy holidays to you and yours,
> -db
> :)
> 

> It seems so!  I will say that I mange everything with sourcetree so it may automatically see its a submodule and add `—recurse-submodules` to the pull call.  Both parse as expected!
> 
> Happy Holidays as well!  I’ll talk to you in the new year!
> 
> David

> Thanks!

**Pull request merged**
