### PR TITLE
Fix a configuration issue where the modulation scheme wouldn't serialize.

### LINKED ISSUE #95: Use ASCII format for configuration file
PyBERT used to use an ASCII format for the configuration file.  This allowed me to create files with a program and then start PyBERT and I'd pick the configuration file I wanted to use for that simulation.  Now that PyBERT 3.4.2 uses a binary format, I can't do that.  Consider loading and saving the old or new formats or switching back to the ASCII format.

### PR DESCRIPTION
**Pull request by jdpatt**
Fixes #95.  Basically, pyyaml didn't know how to serialize or deserialize the List Trait.  This reverts the change to pickle back to pyyaml.

### CODE REVIEW

**Review by capn-freako — COMMENTED** [review]
Thanks, David!

I've copied your change to `pybert_cfg.py` into my working copy.

Your changes to `pybert_view.py` are a redundant subset of the changes I've already made to my working copy.
(My current working code will allow us to choose between pickling and yamling, via a single global define near the top of the code.)

I'll try to get a pull request, which includes the work you've done here as well as some other fixes, submitted for review by EOW.

**Comment by jdpatt** [comment]
Okay, after you merge your copy; close/delete this PR.  Just pushed something that will also resolve #77 .

**Comment by capn-freako** [comment]
Thanks, @jdpatt !

**Comment by capn-freako** [comment]
All suggested changes (or, equivalent alternatives) accepted and incorporated into my sandbox, soon to be pushed as: 3.5.0.0.

**Pull request closed without merging**
