### PR TITLE
New layout

### PR DESCRIPTION
**Pull request by capn-freako**
Hi David,

I'm creating this pull request, before merging, to give you a chance to review my changes.
Note that (I think) there're no technical changes here; only aesthetic ones.
I've given the GUI a complete make-over, taking advantage of the availability of "sub-tabbed" frames, in the **Enthought** _Traits/UI_ framework.
(I've been waiting for this capability for a while now.)

Cheers,
-db

### CODE REVIEW

**Comment by jdpatt** [comment]
On my windows machine right now: The AMI checkboxes for both TX and RX don't seem to work.  Clicking on Results -> Outputs causes PyBERT to crash with a LinePlot error:

```
chaco\lineplot.py:255: UserWarning: Chaco.LinePlot: len(value) 958 - len(index) 400 = 558
 % (len(value), len(index), size_diff))
```

Besides that, I really like the tab window in a tab window view!  Makes the tabs much less clustered.  Might even make sense to have  "Config", "Tx", Rx", "Channel", and etc...  I know Tx/Rx impedance is used to solve the channel impulse but now we have Tx controls on both the config and channel tabs.  

I could even seen the main tab having a visual of the full channel (Tx+Channel + Rx) that kinda highlights the current config. across the other tabs.

Excited to see what `draw_channel` will do for the channel view.  Is that part of your simbeor work or do you plan to incorporate that for the current channel view?

**Comment by capn-freako** [comment]
Hi David,

Thanks for the feedback!
I’ve replied below, to preserve context.

Thanks,
-db


> On Oct 26, 2019, at 5:51 PM, David Patterson <notifications@github.com> wrote:
> 
> On my windows machine right now: The AMI checkboxes for both TX and RX don't seem to work.  
> 
They only become enabled after you’ve loaded a DLL and AMI file; did you do that?
> Clicking on Results -> Outputs causes PyBERT to crash with a LinePlot error:
> 
> chaco\lineplot.py:255: UserWarning: Chaco.LinePlot: len(value) 958 - len(index) 400 = 558
>  % (len(value), len(index), size_diff))
I see this often, but it doesn’t cause PyBERT to crash.
Is it actually causing PyBERT to crash, in your case?
> Besides that, I really like the tab window in a tab window view! Makes the tabs much less clustered.
> 
Thanks! :)
> Might even make sense to have "Config", "Tx", Rx", "Channel", and etc... I know Tx/Rx impedance is used to solve the channel impulse but now we have Tx controls on both the config and channel tabs.
> 
> 
Haha! Great minds think alike. ;-)
Yeah, I definitely want to consolidate the Tx/Rx split.
Maybe we could knock around a few ideas sometime soon?
> I could even seen the main tab having a visual of the full channel (Tx+Channel + Rx) that kinda highlights the current config. across the other tabs.
> 
> 
Oh, I REALLY like that idea.
> Excited to see what draw_channel will do for the channel view. Is that part of your simbeor work or do you plan to incorporate that for the current channel view?
> 
> 
Yes, this new release is sort of an “un-Simbeor’d” version of the simbeor branch.
I wasn’t careful to separate the work I’m doing with Yuriy and crew from the new layout changes.
And, since we’re not quite ready to release the fully Simbeor-integrated version, I had to do some surgery. :(

**Comment by capn-freako** [comment]
David,

I merged, even though our conversation hasn't been brought  to closure, because I want to get started on the Tx/Rx split. And I want to be using the new layout, to do that work.

If we find something that is really broken, we'll address it on a separate maintenance branch; okay?

Thanks,
-db

**Comment by jdpatt** [comment]
> They only become enabled after you’ve loaded a DLL and AMI file; did you do that?

Yeah, I forgot about that with the AMI models.  My develop branch has changed that some.  So disregard.

> I see this often, but it doesn’t cause PyBERT to crash.
Is it actually causing PyBERT to crash, in your case?

It did crash in this case but it could be a different exception that is being masked.  Doesn't crash on my main machine. (osx)

> Maybe we could knock around a few ideas sometime soon?

Sure, I'll reply to your email and setup a time.

**Pull request merged**
